library(magrittr)
library(readr)
library(ggplot2)
library(tidyr)
library(dplyr)
library(Xmisc)
parser <- ArgumentParser$new()
parser$add_description("R script for generating figures associated with PRS results and their phenotypes. Currently (8/26) creates a histogram and a scatter plot, with points labelled by case/control disease condition.")
parser$add_argument("--prs_results", type = 'character', help = "Path to file with PRS scores, listed in a TSV by ID and score", default = "/work-zfs/abattle4/ashton/prs_dev/scratch/calc_prs_testing/beta_results_test.tsv")
parser$add_argument("--pheno", type = "character", help = "Path to phenotype file, as given by Marios' analysis.", default = "/work-zfs/abattle4/ashton/prs_dev/CHS_race1_toy/pheno_mendrand.txt")
parser$add_argument("--output", type = "character", help = "Output file path and suffix.")
parser$add_argument('--help',type='logical',action='store_true',help='Print the help page')
parser$helpme()
args <- parser$get_args()


'%ni%' <- Negate('%in%')

prs <- read_tsv(args$prs_results)
phenos <- read_tsv(args$pheno) %>% rename(ID = IID)
MI_pred <- inner_join(prs, phenos) %>% select(ID, Score, MI)
MI_pred$MI <- as.factor(MI_pred$MI)
ggplot(MI_pred,aes(x=Score, color = MI)) + geom_histogram() +labs(x="PRS", y="Count", title="Distribution of PRS Scores")
ggsave(filename = paste0(args$output, ".histogram.png"))
ggplot(MI_pred, aes(x=c(0), y = Score, color = MI)) + geom_jitter(position=position_jitter(0.1)) + xlim(-0.4, 0.4) + theme(axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank())
ggsave(filename = paste0(args$output, ".dotplot.png"))